"""content default datetime

Revision ID: 25713c4de770
Revises: 4354c2b0be20
Create Date: 2014-09-19 20:51:54.771405

"""

# revision identifiers, used by Alembic.
revision = '25713c4de770'
down_revision = '4354c2b0be20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
