"""add content.content_description

Revision ID: 2f9fd087ac21
Revises: 36ee5ae2176a
Create Date: 2014-09-15 20:55:37.457625

"""

# revision identifiers, used by Alembic.
revision = '2f9fd087ac21'
down_revision = '36ee5ae2176a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('content_description', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'content_description')
    ### end Alembic commands ###
