"""content default datetime2

Revision ID: 3005f024ffd8
Revises: 25713c4de770
Create Date: 2014-09-19 20:55:03.978248

"""

# revision identifiers, used by Alembic.
revision = '3005f024ffd8'
down_revision = '25713c4de770'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
