"""add content

Revision ID: 36ee5ae2176a
Revises: c250bce69a9
Create Date: 2014-09-15 20:44:33.495852

"""

# revision identifiers, used by Alembic.
revision = '36ee5ae2176a'
down_revision = 'c250bce69a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_name', sa.String(length=64), nullable=True),
    sa.Column('content_keywords', sa.String(length=256), nullable=True),
    sa.Column('content_content', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contents')
    ### end Alembic commands ###
