"""add content datetime and topic alias

Revision ID: 4354c2b0be20
Revises: e4f721e0d2a
Create Date: 2014-09-19 11:02:38.062388

"""

# revision identifiers, used by Alembic.
revision = '4354c2b0be20'
down_revision = 'e4f721e0d2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('content_datetime', sa.DateTime(), nullable=True))
    op.add_column('topics', sa.Column('topic_alias', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'topics', ['topic_alias'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics')
    op.drop_column('topics', 'topic_alias')
    op.drop_column('contents', 'content_datetime')
    ### end Alembic commands ###
