"""initial migration

Revision ID: c250bce69a9
Revises: None
Create Date: 2014-09-15 00:29:53.568993

"""

# revision identifiers, used by Alembic.
revision = 'c250bce69a9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=64), nullable=True),
    sa.Column('topic_keywords', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    ### end Alembic commands ###
